apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: java-k8s-gradle-gcloud
      image: gcr.io/ingress-lms-276014/java-k8s-gradle-gcloud:1.0
      command: ["tail", "-f", "/dev/null"]  # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
      imagePullPolicy: Always # use cache or pull image for agent
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
      resources:  # limits the resources your build contaienr
        requests:
          memory: "100m"
          cpu: "50m"
        limits:
          memory: "500m"
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock